export const LESSONS = [
  {
    id: "first-route",
    title: "Your first API route",
    subtitle: "Give a client a useful response",
    duration: "4 min",
    level: "Foundations",
    intro: "An API route connects an HTTP method and a URL to the Python function that handles a request. FastAPI uses decorators such as @app.get to declare that connection.",
    code: 'from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get("/")\ndef home():\n    return {"message": "Hello, Lagos"}',
    conceptHeading: "A route has two parts",
    concept: "The decorator names the method and path. The function below it creates the response. FastAPI converts a returned Python dictionary into JSON for the client.",
    challenge: "Which method and path handle GET requests to the home URL in this example?",
    options: [{ id: "a", text: "POST /home" }, { id: "b", text: "GET /" }, { id: "c", text: "GET /home" }],
    answerId: "b",
    feedback: "Look at the decorator: @app.get(\"/\") sets both the HTTP method and path.",
    refresher: "Read the decorator from left to right: get means the HTTP GET method, and / is the root path.",
    source: "FastAPI · First Steps",
    sourceUrl: "https://fastapi.tiangolo.com/tutorial/first-steps/",
    sourceLicense: "FastAPI docs · MIT",
    sourceLicenseUrl: "https://github.com/fastapi/fastapi/blob/master/LICENSE",
    sourceCheckedAt: "29 Sep 2026"
  },
  {
    id: "path-params",
    title: "Read a value from the URL",
    subtitle: "Path parameters make routes reusable",
    duration: "5 min",
    level: "Routing",
    intro: "A path parameter captures part of a URL, such as a learner ID. FastAPI matches the parameter in the route and passes its value to the function.",
    code: 'from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get("/learners/{learner_id}")\ndef read_learner(learner_id: int):\n    return {"learner_id": learner_id}',
    conceptHeading: "The URL supplies the value",
    concept: "In /learners/42, the value 42 is bound to learner_id. The int annotation tells FastAPI to parse and validate that value as an integer.",
    challenge: "For /learners/42, what value reaches read_learner as learner_id?",
    options: [{ id: "a", text: "The string {learner_id}" }, { id: "b", text: "The integer 42" }, { id: "c", text: "No value; it is a query parameter" }],
    answerId: "b",
    feedback: "The named segment in the URL is captured. Here the int annotation parses 42 as an integer.",
    refresher: "A value inside braces in the route is a path parameter. The URL /learners/42 supplies 42.",
    source: "FastAPI · Path Parameters",
    sourceUrl: "https://fastapi.tiangolo.com/tutorial/path-params/",
    sourceLicense: "FastAPI docs · MIT",
    sourceLicenseUrl: "https://github.com/fastapi/fastapi/blob/master/LICENSE",
    sourceCheckedAt: "29 Sep 2026"
  },
  {
    id: "request-body",
    title: "Receive JSON safely",
    subtitle: "Describe the shape of incoming data",
    duration: "6 min",
    level: "Request data",
    intro: "A client often sends data in a request body, for example when creating a record. A Pydantic model describes the expected fields, and FastAPI validates incoming JSON against it.",
    code: 'from pydantic import BaseModel\n\nclass Note(BaseModel):\n    title: str\n    done: bool = False\n\n@app.post("/notes")\ndef create_note(note: Note):\n    return note',
    conceptHeading: "The model is a contract",
    concept: "The Note model expects a string title and an optional boolean done field. FastAPI reads the JSON request body, validates it, and gives the function a Note object.",
    challenge: "Which input belongs in the JSON request body for this model?",
    options: [{ id: "a", text: '{"title": "Study routes"}' }, { id: "b", text: "/notes?title=Study routes" }, { id: "c", text: "A plain-text response from the server" }],
    answerId: "a",
    feedback: "The model is a request body parameter, so the client sends its fields as JSON.",
    refresher: "A Pydantic model used as a route parameter describes a request body. Send its fields as JSON.",
    source: "FastAPI · Request Body",
    sourceUrl: "https://fastapi.tiangolo.com/tutorial/body/",
    sourceLicense: "FastAPI docs · MIT",
    sourceLicenseUrl: "https://github.com/fastapi/fastapi/blob/master/LICENSE",
    sourceCheckedAt: "29 Sep 2026"
  },
  {
    id: "validation",
    title: "Let validation catch bad input",
    subtitle: "Use types as guardrails",
    duration: "5 min",
    level: "Validation",
    intro: "A type declaration helps make an API predictable. FastAPI uses Pydantic to parse and validate data, then returns a clear validation error when the submitted value does not match the expected shape.",
    code: 'from pydantic import BaseModel\n\nclass Learner(BaseModel):\n    name: str\n    weekly_hours: int\n\n# Valid JSON: {"name": "Ada", "weekly_hours": 4}\n# Invalid: {"name": "Ada", "weekly_hours": "many"}',
    conceptHeading: "Validation protects the boundary",
    concept: "External input is not automatically trustworthy. Declaring expected types makes the request contract visible and lets the framework reject values it cannot parse.",
    challenge: "The API expects weekly_hours: int. Which value fits that field?",
    options: [{ id: "a", text: '"many"' }, { id: "b", text: "4" }, { id: "c", text: "null" }],
    answerId: "b",
    feedback: "The field is declared as int, so a whole number such as 4 matches the expected type.",
    refresher: "Compare the input to the model: weekly_hours is an integer. A quoted word is text, not an integer.",
    source: "FastAPI · Request Body and Validation",
    sourceUrl: "https://fastapi.tiangolo.com/tutorial/body/",
    sourceLicense: "FastAPI docs · MIT",
    sourceLicenseUrl: "https://github.com/fastapi/fastapi/blob/master/LICENSE",
    sourceCheckedAt: "29 Sep 2026"
  },
  {
    id: "status-codes",
    title: "Tell clients what happened",
    subtitle: "Choose a useful response status",
    duration: "5 min",
    level: "Responses",
    intro: "An HTTP status code tells a client the broad result of a request. When an API successfully creates a resource, 201 Created is a common and explicit response.",
    code: 'from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.post("/notes", status_code=201)\ndef create_note():\n    return {"created": True}',
    conceptHeading: "Status is part of the response",
    concept: "FastAPI lets a route declare its normal response status with status_code. Use a code that communicates the result to the client; do not treat status codes as decoration.",
    challenge: "Which status code most clearly signals that a request created a resource?",
    options: [{ id: "a", text: "200 OK" }, { id: "b", text: "201 Created" }, { id: "c", text: "404 Not Found" }],
    answerId: "b",
    feedback: "201 Created specifically communicates successful resource creation.",
    refresher: "A successful response can have different meanings. 201 Created says a resource was created.",
    source: "FastAPI · Response Status Code",
    sourceUrl: "https://fastapi.tiangolo.com/tutorial/response-status-code/",
    sourceLicense: "FastAPI docs · MIT",
    sourceLicenseUrl: "https://github.com/fastapi/fastapi/blob/master/LICENSE",
    sourceCheckedAt: "29 Sep 2026"
  }
];

export const PATHS = {
  beginner: { title: "Beginner route", description: "Start with the request and route basics, then build confidence with validation and response behavior.", order: LESSONS.map((lesson) => lesson.id) },
  fast: { title: "Fast-track route", description: "Try the practical challenge first, then use the explanation to review concepts you want to strengthen.", order: LESSONS.map((lesson) => lesson.id) }
};

export const OPPORTUNITY = {
  title: "Backend Intern · Nile",
  location: "Remote · Lagos eligible",
  summary: "Role focus: scale database queries, integrate delivery logs, and optimize checkout routing. Check Nile's current page for eligibility and application details.",
  url: "https://www.usenile.co/careers",
  checkedAt: "29 Sep 2026"
};
